### ISSUE TITLE
install redis tracker rasa & mac

### ISSUE THREAD

**Issue by pksvv** [pksvv/rasa3.0#3]
```
mkdir redis && cd redis
curl -O http://download.redis.io/redis-stable.tar.gz
tar xzvf redis-stable.tar.gz
cd redis-stable
make
make test
sudo make install
```

```
mkdir redis && cd redis – Creates a folder called ‘redis’ and moves you to the newly created folder.

curl -O http://download.redis.io/redis-stable.tar.gz – Downloads the Redis installation archive.

tar xzvf redis-stable.tar.gz – Unpacks the ‘redis-stable‘ installation archive.

cd redis-stable – Moves you to the ‘redis-stable’ folder.
```

**Start by**

`redis-server
`

**Endpoints.yml**

```
tracker_store:
   type: redis
   url: "127.0.0.1"
   port: "6379"
   db: "0"
   password: 
   use_ssl: false
```
